### PR TITLE
build: Migrate dependabot config to v2

### PR DESCRIPTION
**Pull request by pefoley2**
Migrate the existing dependabot config to the v2 format

### CODE REVIEW

**Review by Laur04 — APPROVED** [review]
LGTM

**Comment by pefoley2** [comment]
Fwiw, I believe that this change needs to go into master so that it'll actually be picked up.

**Comment by Laur04** [comment]
Yea, it does. I haven’t gotten around to your other PR yet today - I’m going to put the recent changes to master all together.

**Comment by pefoley2** [comment]
SGTM.

**Pull request merged**
