### PR TITLE
chore(emailfwd): change senior email forward message

### PR DESCRIPTION
**Pull request by shahsalonik**
## Proposed changes
- Change "By the end of the summer after graduation" to "At the conclusion of the school year"

## Brief description of rationale
Makes more sense for seniors (because they won't be coming back to TJ)

### CODE REVIEW

**Review by etnguyen03 — APPROVED** [review]
LGTM pending CI - and we will merge in some time - but you didn't have to reopen this PR (you could have [done something like this](https://gitbetter.substack.com/p/how-to-squash-git-commits)).

**Comment by shahsalonik** [comment]
Oh, ok that makes a lot more sense. I tried to do something similar earlier but it wouldn't let me commit the change that I made, so I scrapped that and made a new pull request. Thanks for the source!

**Review by Laur04 — CHANGES_REQUESTED** [review]
LGTM, but the commit message needs to include the issue closing. It should be something like:
```
chore(emailfwd): change senior email forward message

closes #1124
```
You can fix this with `git commit -amend`

**Comment by etnguyen03** [comment]
The commit message should have two new lines -- not the one line that you have currently.

So `closes #1124` should be on a separate line than the rest of the message, like this:

```
chore(emailfwd): change senior email forward message

closes #1124
```

**Comment by Laur04** [comment]
You can see the `build` CI is complaining...there should be a blank line between "chore(emailfwd): change senior email forward message" and "closes #1124". It should be:
```
chore(emailfwd): change senior email forward message
<nothing on this line, just hit enter and move onto the third line>
closes #1124
```

**Comment by shahsalonik** [comment]
Yup, I'll fix that now.

**Review by Laur04 — APPROVED** [review]
LGTM

**Pull request merged**
