### PR TITLE
feat(polls): Add support for Standard Other question

### LINKED ISSUE #1525: Polls: Support "Standard Other" question type
## Feature description
- Question type that allows users to select an answer (like in `Standard`) but also adds an "Other" option where users can write-in a response.

Example:
What is your favorite fruit?
- Apples
- Oranges
- Bananas
- Other: _______________ (textbox)

## Rationale for adding feature
- Standard other (STO) is already a question type in the Polls app. However, it hasn't been implemented.
- It's useful

## Suggested implementation(s) (if applicable)
- Look at implementations of the Standard and Short Response question types.

### PR DESCRIPTION
**Pull request by avnithv**
## Proposed changes
- Support Standard other (STO) questions in polls, which are basically multiple choice questions with an Other option
- In viewing results, it shows all of the answers that were written in the Other field

## Brief description of rationale
STO questions are cool and allow for more flexible types of questions/polls.

Closes #1525

### CODE REVIEW

**Review by alanzhu0 — APPROVED** [review]
LGTM
Great work!

**Review by shahsalonik — CHANGES_REQUESTED** [review]
LGTM! Could you fix one of the checks breaking and push again? You should just have to run `./scripts/format.sh`.

**Comment by alanzhu0** [comment]
Just jumping in - the check that's failing is build. Running `scripts/build_sources.sh` should fix that. You may have already done this before (you passed the other checks so you prepared for CI well), but build sources only works after you commit your changes which may be why it didn't get applied.

**Comment by avnithv** [comment]
Hi. I ran ```scripts/build_sources.sh``` and pushed again.

**Review by shahsalonik — APPROVED** [review]
LGTM

**Pull request merged**
