### PR TITLE
Hide scrollbars on signage

### PR DESCRIPTION
**Pull request by anonymoose2**
Micro-optimization. No idea if anything else needs to be done.

### CODE REVIEW

**Comment by anonymoose2** [comment]
@naitian: Just realized this won't affect iframes, so the announcements page would still have a scrollbar. Would `signage.page.scss` be the place to add it so that doesn't happen?

**Comment by anonymoose2** [comment]
@naitian Is this ready to be merged?

**Comment by anonymoose2** [comment]
Ok, that's weird. Travis fails, but `./setup.py test` locally gives no errors.

**Comment by theo-o** [comment]
Line 251 of `settings/__init__.py` is too long and failing the flake line test (150 char limit).

**Pull request merged**
