### PR TITLE
Minor Fixes

### PR DESCRIPTION
**Pull request by tcyrus**
Some Accessibility Fixes and Template Fixes

### CODE REVIEW

**Comment by pefoley2** [comment]
What is aria-label?

**Comment by tcyrus** [comment]
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute

**Comment by pefoley2** [comment]
You should note that somewhere then.
Is this the only usage? Should it be added elsewhere?
Is there something specific about this element that requires it?

**Comment by jwoglom** [comment]
Aria-label is a standardized accessibility tag; nothing wrong with having it there

**Comment by pefoley2** [comment]
@jwoglom I'm not saying it's wrong, just raising some other possible concerns :)

**Pull request merged**
