### PR TITLE
signups/user API tweaks

### PR DESCRIPTION
**Pull request by naitian**
- Added block_letter to response
- Now results are sorted by date and then block

### CODE REVIEW

**Comment by pefoley2** [comment]
Please run flake8.

**Comment by pefoley2** [comment]
Note that you can most likely run autopep8 to fix the formatting for you.

**Comment by pefoley2** [comment]
Looks fine otherwise, but I'll defer to @jwoglom

**Comment by jwoglom** [comment]
Looks good to me

**Pull request merged**
