### PR TITLE
chore(eighth): replace text instances of 48 hour presign with 2 day

### LINKED ISSUE #1577: Complete change from 48 hour pre-signup to 2 day custom time
Commit https://github.com/tjcsl/ion/commit/bc1c21252c904fd25508d3da24f8563bac27c8b8 added the feature for a custom 2 day presign time, changing it from the old 48 hour restriction.

However, the 48 hour text (not logic) still exists in the Ion codebase. Those need to be replaced with the 2 day text.

### PR DESCRIPTION
**Pull request by shrysjain**
Closes #1577

## Proposed changes
- Replaced all 48 hour presign text instances in Ion with the 2 day text 

## Brief description of rationale
- Consistency in text across the codebase

### CODE REVIEW

**Comment by shrysjain** [comment]
@alanzhu0 how about now?

**Review by alanzhu0 — CHANGES_REQUESTED** [review]
Looks good now. Can you combine/squash the two commits into one?

**Comment by shrysjain** [comment]
@alanzhu0 done 👍

**Review by alanzhu0 — APPROVED** [review]

**Comment by alanzhu0** [comment]
Congrats on your first contribution!

**Comment by shrysjain** [comment]
thanks! first of hopefully many :)

**Pull request merged**
