### PR TITLE
Improved Accessibility

### PR DESCRIPTION
**Pull request by tcyrus**
Second Try at this Pull Request (#385)

### CODE REVIEW

**Comment by pefoley2** [comment]
Note that you can just force push to the branch, you don't need to make a new PR.

**Comment by pefoley2** [comment]
Coveralls is down for maintenance.
LGTM.
@jwoglom ?

**Comment by pefoley2** [comment]
@tcyrus, might want to get jwoglom to merge your PRs in future.

**Comment by tcyrus** [comment]
ok

**Pull request merged**
