### PR TITLE
refactor: focus searchbar on keydown and better tab nav

### PR DESCRIPTION
**Pull request by alanzhu0**
## Proposed changes
- Typing goes to the search bar on dashboard page
- Tab goes to search bar -> View Eighth Profile -> left-side menu on profile page

## Brief description of rationale
- Email from Dr. Gabor

### CODE REVIEW

**Comment by Rushilwiz** [comment]
hah! you beat me to this, I was just working on it when I got the email.

**Comment by alanzhu1** [comment]
Haha, love the race! Maybe your implementation is more elegant? Mine is pretty crude.
We probably should've communicated too lol

**Comment by Rushilwiz** [comment]
For sure. I think your implementation is workable, but I think this can be achieved without JS. You're looking for the `autofocus` and `tabindex` fields, I think, HTML already has a lot of great ARIA stuff that does exactly what you want.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

So just

```html
<input autofocus tabindex=0 type="text" name="q" value="{% if search_query %}{{ search_query }}{% endif %}" placeholder="Search directory and more" aria-label="Search directory and more">
```

should work, and then just increment the tab index on the other elements instead of using JS.

**Comment by alanzhu1** [comment]
Yeah, that was actually exactly my first approach but I ran into two issues: 
1. I didn't want the cursor to be already blinking in the search field upon load, just for aesthetics (not a big issue)
2. Whenever I used `tabindex`, any value other than 0 didn't work - positive values acted as if they were negative values. Maybe it was a problem on my end? It was pretty weird.
I definitely agree an HTML-only approach would be better though.

**Review by shahsalonik — APPROVED** [review]
LGTM

**Pull request merged**
