### PR TITLE
Removed hover/shading on hamburger icon

### PR DESCRIPTION
**Pull request by jacobajit**

### CODE REVIEW

**Comment by jamesthoughton** [comment]
@jacobajit I prefer how it is now :(

**Comment by jacobajit** [comment]
IMO it looks more Material and up to date with the revision; @jwoglom thought it was alright.

**Comment by jamesthoughton** [comment]
if you remove it under the hamburger button, then you probably have to remove it from under the username dropdown toggle too (and imo that absolutely should not go)

**Comment by pefoley2** [comment]
If you want to do this, please keep the ui consistent.
What about pulling an inbox and having the color of the hamburger menu slightly change?

**Comment by jacobajit** [comment]
Color change on hover is probably the best solution, for all icons. However, the icons should return to their original color, like the Inbox hamburger. If someone could fix this later

**Comment by pefoley2** [comment]
Sure, but let's keep it as-is until we have a complete fix that keeps the UI internally consistent.
Closing for now, feel free to make a new PR w/ changes to all the UI elements.

**Pull request closed without merging**
