### PR TITLE
fix(events): stop showing 'creator' and 'approved by' that is None

### LINKED ISSUE #1127: Events page shows the user who approved and created even if it is None
This issue is being created for training purposes. PLEASE DO NOT SUBMIT A PULL REQUEST FOR THIS ISSUE UNLESS YOU ARE EXPLICITLY AUTHORIZED TO DO SO.

## Steps to reproduce
1. Add an event(s) with [this script](https://github.com/tjcsl/ion/blob/master/intranet/apps/events/management/commands/import_sports.py) or the function it calls
2. Look at `/events`, both as an admin and not as one

## Expected behavior
See the screenshot below (in Actual behavior). If there is no person who created the activity, then the activity should not show who created the activity (because there is no person who did). ([see this line](https://github.com/tjcsl/ion/blob/158881310895fb5bac4525c2bc6a878677846f73/intranet/templates/events/event.html#L54).)

Additionally, as an eighth admin, "approved by" probably shouldn't show if there is no approver. See [this](https://github.com/tjcsl/ion/blob/158881310895fb5bac4525c2bc6a878677846f73/intranet/templates/events/event.html#L90).

## Actual behavior
image

### PR DESCRIPTION
**Pull request by ramnreddy15**
Closes #1127

### CODE REVIEW

**Comment by etnguyen03** [comment]
Please [squash the two commits](https://linuxhint.com/how-to-squash-git-commits/).

**Comment by ramnreddy15** [comment]
> Please [squash the two commits](https://linuxhint.com/how-to-squash-git-commits/).

Commits have been squashed.

**Comment by Laur04** [comment]
Please change “stops” to “stop”. Commit messages always use the imperative tense.

**Comment by etnguyen03** [comment]
Also, can you remove the second set of commit messages?

image

**Comment by ramnreddy15** [comment]
> Please change “stops” to “stop”. Commit messages always use the imperative tense.



> Also, can you remove the second set of commit messages?
> 
> image

Done. Should I change the PR header as well? From "stops" to "stop".

**Review by etnguyen03 — APPROVED** [review]
LGTM, pending CI

**Comment by Laur04** [comment]
@ramnreddy15 feel free to pick up another issue if you want to.

**Comment by ramnreddy15** [comment]
> @ramnreddy15 feel free to pick up another issue if you want to.

Will do! It was pretty fun, so I will try another once I finish with APs.

**Pull request merged**
