### PR TITLE
feat(dev): better fake data

### PR DESCRIPTION
**Pull request by NotFish232**
Supercedes #1475
## Proposed changes
- delete long json and text files containing data
- include scripts to generate data for users, scripts, and activities
## Brief description of rationale
- hard coding in data is bad practice
- instead generate the data using scripts

### CODE REVIEW

**Review by alanzhu0 — CHANGES_REQUESTED** [review]
Please resolve merge conflicts.

**Comment by alanzhu0** [comment]
So, I suspect the CI is failing because it's an old run. But for some reason I can't re-run it. Can you just force push with no changes to trigger a re-run? After CI passes this is good for merge.

**Comment by NotFish232** [comment]
I force pushed and CI still seems to be failing. Also reran ./scripts/build_sources.sh but no change.

**Review by alanzhu0 — APPROVED** [review]
Good job Justin

**Comment by NotFish232** [comment]
Thanks Alan Zhu.

**Pull request merged**
