### PR TITLE
build: fix channels 3 error

### PR DESCRIPTION
**Pull request by etnguyen03**
## Proposed changes
- Fix error caused by #1150 

## Brief description of rationale
Changelogs - https://channels.readthedocs.io/en/latest/releases/3.0.0.html

### CODE REVIEW

**Review by Laur04 — APPROVED** [review]
Assuming CI, LGTM

**Comment by pefoley2** [comment]
Wait, how did that pass the tests?

**Comment by etnguyen03** [comment]
> Wait, how did that pass the tests?

There are no test cases that cover websockets. Support for async test cases, I believe, is added in Django 3

**Comment by pefoley2** [comment]
Oh, fun :|

**Pull request merged**
