### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by anonymoose2**
## Proposed changes
- Bump dependencies

## Brief description of rationale
Some of our dependencies are out of date.

### CODE REVIEW

**Comment by anonymoose2** [comment]
CI is failing because the Celery fix in https://github.com/celery/celery/issues/6145 has not yet been released.

**Comment by anonymoose2** [comment]
Celery v4.4.5 has released, and it fixes the `future` issue.

**Comment by anonymoose2** [comment]
@theo-o The [Travis build](https://travis-ci.org/github/tjcsl/ion/builds/696445361) has passed, though it's not showing up for some reason. Is this OK to merge?

**Comment by theo-o** [comment]
> @theo-o The [Travis build](https://travis-ci.org/github/tjcsl/ion/builds/696445361) has passed, though it's not showing up for some reason. Is this OK to merge?

Permission to override granted.

**Pull request merged**
