### PR TITLE
remove extra s in polls

### PR DESCRIPTION
**Pull request by evanyeyeye**

### CODE REVIEW

**Comment by pefoley2** [comment]
Please remove the file from dist/ and run ./setup.py egg_info

**Comment by evanyeyeye** [comment]
@pefoley2 - Ran the command and removed dist, but the Travis CI build failed? Any advice?

**Comment by pefoley2** [comment]
If you rebase onto the dev branch, and/or cherry-pick the top commit from dev, it should work now.
We were missing a stub for mypy.

**Comment by pefoley2** [comment]
Note that this should probably be targeted to merge into the dev branch, not master

**Comment by evanyeyeye** [comment]
Ok, I'll make a pr for the dev branch.

**Pull request closed without merging**
