### PR TITLE
feat(bus): Implement Ion bus game (closes #1653)

### LINKED ISSUE #1653: Implement Ion bus game
## Feature description
Implement the bus game feature in the bus app. Users will access this by clicking on an empty bus spot then clicking skrt skrt. Feel free to make whatever game you want; just have it thematically use a bus somehow. Potential ideas could include some sort of crossy road themed game.

## Rationale for adding feature
Makes Ion more awesome.

### PR DESCRIPTION
**Pull request by Catelyn-Dao**
## Proposed changes
- Implement new Ion Bus Game into Ion Bus tab
- Revised prior game commits

## Brief description of rationale
- Make Ion more fun
- Add some personality to the page

## Future Improvements
- Create visible movement keys to implement on signage
- Add more complexity (e.g. more terrain, varying roads, progress bar)

### CODE REVIEW

**Comment by shrysjain** [comment]
@alanzhu0 @NotFish232 ready for review :)

**Comment by alanzhu0** [comment]
Possible bug: if you slow down to the min speed at the beginning, then speed up, it doesn't appear to actually speed up again. 
Also, need a mobile version or disable going to the game on mobile for now.

**Comment by Catelyn-Dao** [comment]
# New features
- Disabled on mobile
- Added start screen
- Added instructions/controls
- Change scoring from arbitrary distance to time
- Added obstacles (deer, bikers)
- Added a progress bar
- Added a wider variety of cars/vehicles
- A bunch of easter eggs

**Comment by shrysjain** [comment]
moved to [1712](https://github.com/tjcsl/ion/pull/1712)

**Pull request closed without merging**
