### PR TITLE
Lossless Compression of all Images

### PR DESCRIPTION
**Pull request by tcyrus**

### CODE REVIEW

**Comment by jwoglom** [comment]
@tcyrus What exactly did you change and how?

**Comment by pefoley2** [comment]
@tcyrus Please provide steps to exactly reproduce your result when modifying binaries.

**Comment by pefoley2** [comment]
bump

**Comment by tcyrus** [comment]
Used [ImageOptim-CLI](https://github.com/JamieMason/ImageOptim-CLI) and [gifsicle](https://github.com/kohler/gifsicle)

**Comment by fwilson42** [comment]
@tcyrus can you at least write a script / provide better documentation than just the tools you used? right now when new images are added there's significant research involved trying to figure out how you did this

also when someone asks for clarification on a pull request and you merge it immediately after providing it, it's generally not considered good form. next time if you could please wait for the person who requested the additional information, or someone else, to merge your pull request that would probably be a better idea.

this pr helps improve load times but please write documentation for it :smile:

cc @pefoley2, @jwoglom 
thanks!

**Comment by jwoglom** [comment]
This process seems to have noticeably (by several pixel values) changed the colors on at least some of the images -- particularly the default profile pic pngs. We run everything through pagespeed anyway in production, so I don't think this is necessary. Reverting commit.

**Pull request merged**
