### PR TITLE
Added Go-To Actions for Gmail

### PR DESCRIPTION
**Pull request by tcyrus**
https://developers.google.com/gmail/markup/reference/go-to-action

### CODE REVIEW

**Comment by pefoley2** [comment]
This should be re-factored to use templates to reduce duplication.
Also add a link to the official reference documentation in a comment.

**Comment by jwoglom** [comment]
Agreed

**Comment by tcyrus** [comment]
https://developers.google.com/gmail/markup/reference/go-to-action

**Comment by pefoley2** [comment]
Still needs to resolve the comments and should probably be rebased and squashed into one commit.
Don't worry about the coverage "failure", though more tests are always good.

**Comment by jwoglom** [comment]
Refactor needed

**Pull request merged**
