### PR TITLE
fix: use IMEI instead of serial number for phone registration

### PR DESCRIPTION
**Pull request by nkenschaft**
Don't mind all the extra files... I hadn't pulled in a while so it got messy.

### CODE REVIEW

**Comment by Laur04** [comment]
You should rebase you commits against `dev` so that the extra files don't appear as part of the commit.

**Comment by etnguyen03** [comment]
Please rebase against the latest `dev`:

```bash
git remote add upstream git@github.com:tjcsl/ion.git
git fetch upstream
git checkout dev
git rebase upstream/dev
```

**Comment by anonymoose2** [comment]
> Please rebase against the latest `dev`:
> 
> ```shell
> git remote add upstream git@github.com:tjcsl/ion.git
> git fetch upstream
> git checkout dev
> git rebase upstream/dev
> ```

That's what he should have done in the first place. Not sure whether doing that now will fix it...

**Comment by Laur04** [comment]
At this point it's probably easier to copy out your changes, reset your repo (`git reset --hard upstream/dev`) and copy them back in.

**Comment by Laur04** [comment]
Additionally, in the third line of your commit message, please add `closes #1054` to reference the issue that you are closing with this PR.

**Pull request closed without merging**
